<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.sprawler</groupId>
    <artifactId>sprawler-bom</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <packaging>pom</packaging>

    <name>Sprawler BOM</name>
    <description>Bill of Materials for Sprawler dependencies</description>

    <properties>
        <!-- Java/Build version-->
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>

        <!-- Dependencies versions -->
        <netty.version>4.2.15.Final</netty.version>
        <jackson.version>2.21.4</jackson.version>

        <spring-boot.version>3.5.15</spring-boot.version>
        <spring.version>6.2.19</spring.version>
        <h2.version>2.4.240</h2.version>
        <activemq.version>6.1.8</activemq.version>
        <oauth2-oidc.version>11.37.2</oauth2-oidc.version>
        <java-jwt.version>4.5.0</java-jwt.version>
        <openpdf.version>2.0.5</openpdf.version>

        <!-- Plugin versions -->
        <maven.compiler.version>3.11.0</maven.compiler.version>
        <maven-war.version>3.3.1</maven-war.version>
        <jacoco-maven.version>0.8.12</jacoco-maven.version>
        <maven-surefire.version>3.0.0-M5</maven-surefire.version>
        <maven-pmd.version>3.22.0</maven-pmd.version>
        <maven-checkstyle.version>3.3.1</maven-checkstyle.version>
    </properties>

    <dependencyManagement>
        <dependencies>

            <dependency>
                <groupId>io.netty</groupId>
                <artifactId>netty-bom</artifactId>
                <version>${netty.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

            <dependency>
                <groupId>com.fasterxml.jackson</groupId>
                <artifactId>jackson-bom</artifactId>
                <version>${jackson.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

            <!-- Spring Boot Starters -->
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-dependencies</artifactId>
                <version>${spring-boot.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

            <!-- Spring Framework -->
            <dependency>
                <groupId>org.springframework</groupId>
                <artifactId>spring-jms</artifactId>
                <version>${spring.version}</version>
            </dependency>

            <!-- ActiveMQ -->
            <dependency>
                <groupId>org.apache.activemq</groupId>
                <artifactId>activemq-broker</artifactId>
                <version>${activemq.version}</version>
            </dependency>

            <!-- Database -->
            <dependency>
                <groupId>com.h2database</groupId>
                <artifactId>h2</artifactId>
                <version>${h2.version}</version>
                <scope>runtime</scope>
            </dependency>

            <!-- Security & JWT -->
            <dependency>
                <groupId>com.nimbusds</groupId>
                <artifactId>oauth2-oidc-sdk</artifactId>
                <version>${oauth2-oidc.version}</version>
            </dependency>

            <dependency>
                <groupId>com.auth0</groupId>
                <artifactId>java-jwt</artifactId>
                <version>${java-jwt.version}</version>
            </dependency>

            <!-- PDF Support -->
            <dependency>
                <groupId>com.github.librepdf</groupId>
                <artifactId>openpdf</artifactId>
                <version>${openpdf.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <build>
    </build>

</project>
