name: Continuous Integration - Backend

on:
  pull_request:
    branches:
      - main # Run the workflow only on pull requests to the main branch
    paths:
      - 'backend/**' # Workflow triggered on changes to code
      - '.github/workflows/backend_ci.yml'

jobs:

  build-1:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: .

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'corretto'

      - name: Build with Maven
        run: mvn clean install -q -DskipTests -T 5

  junit-2-1:
    runs-on: ubuntu-latest

    needs: [build-1]

    defaults:
      run:
        working-directory: .

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'corretto'

      - name: Test Junit with Maven
        run: mvn --no-transfer-progress surefire:test

      - name: Generate Test Report
        run: mvn --no-transfer-progress surefire-report:report

      - name: Archive Test Results
        uses: actions/upload-artifact@v3
        with:
          name: junit-test-results
          path: target/surefire-reports/*.xml

      - name: Analyze Test Coverage
        run: mvn --no-transfer-progress jacoco:report

      - name: Archive Coverage Report
        uses: actions/upload-artifact@v3
        with:
          name: jacoco-coverage-report
          path: target/site/jacoco/*.html

      - name: Display Test Results in PR
        uses: dorny/test-reporter@v1
        with:
          name: Surefire
          path: target/surefire-reports/TEST-*.xml
          reporter: java-junit
          fail-on-error: false

  codeql-2-2:
    runs-on: ubuntu-latest

    needs: [build-1]

    defaults:
      run:
        working-directory: .

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: java-kotlin

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'corretto'

      - name: Build with Maven
        run: mvn clean install -q -DskipTests -T 5

      - name: Analyze with CodeQL
        uses: github/codeql-action/analyze@v3