name: Backend Service Continuous Integration - Build

on:
  pull_request:
    branches:
      - main # Run the workflow only on pull requests to the main branch
    paths:
      - 'backend/**' # Workflow triggered on changes to code
      - '.github/workflows/backend_ci.yml'

jobs:

  build-1:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: Checkout Repository and set up JDK environment
        uses: ./.github/actions/setup-repo-java

      - name: Build with Maven
        run: mvn --no-progre clean install -q -DskipTests -T 5