name: Backend Service Continuous Integration - Build

on:
  workflow_run:
    types:
      - completed

jobs:

  build-1:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'corretto'

      - name: Build with Maven
        run: mvn --no-progre clean install -q -DskipTests -T 5