name: Backend Service Continuous Integration

on:
  pull_request:
    branches:
      - main # Run the workflow only on pull requests to the main branch
    paths:
      - 'backend/**' # Workflow triggered on changes to code
      - '.github/workflows/backend_ci.yml'

jobs:

  build-1:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'corretto'

      - name: Build with Maven
        run: mvn --no-transfer-progress clean install -q -DskipTests -T 5

      - name: List Directory Contents
        run: ls -R

      - name: Upload built artifact for future usage
        uses: actions/upload-artifact@v4.3.3
        with:
          name: sprawler-backend-artifact
          path: 'backend/target/*.war'

  junit-2-1:
    runs-on: ubuntu-latest
    needs: ["build-1"]

    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'corretto'

      - name: Run Junit tests and generate Jacoco Report
        run: mvn --no-transfer-progress clean test jacoco:report

      - name: Archive Test Results
        uses: actions/upload-artifact@v4.3.3
        with:
          name: junit-test-results
          path: 'backend/target/surefire-reports/*.xml'

      - name: Archive Coverage Report
        uses: actions/upload-artifact@v4.3.3
        with:
          name: jacoco-coverage-report
          path: 'backend/target/site/jacoco'

      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: 'backend/target/site/jacoco/jacoco.xml'
          fail_ci_if_error: false

  codeql-2-2:
    runs-on: ubuntu-latest
    needs: ["build-1"]

    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'corretto'

      - name: Build with Maven
        run: mvn --no-transfer-progress clean install -q -DskipTests -T 5

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: java-kotlin

      - name: Analyze with CodeQL
        uses: github/codeql-action/analyze@v3

  spotbugs-2-3:
    runs-on: ubuntu-latest
    needs: ["build-1"]

    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'corretto'

      - name: Run Spotbugs analysis
        run: |
          mvn --no-transfer-progress clean spotbugs:spotbugs

      - name: Upload Spotbugs analysis to Github Actions
        uses: jwgmeligmeyling/spotbugs-github-action@master
        with:
          path: '**/spotbugsXml.xml'

  pmd-2-4:
    runs-on: ubuntu-latest
    needs: ["build-1"]

    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'corretto'

      - name: Run PMD analysis
        run: mvn --no-transfer-progress clean pmd:pmd

      - name: Upload PMD analysis to Github Actions
        uses: jwgmeligmeyling/pmd-github-action@master
        with:
          path: '**/pmd.xml'

  checkstyle-2-5:
    runs-on: ubuntu-latest
    needs: ["build-1"]

    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'corretto'

      - name: Run Checkstyle analysis
        run: mvn --no-transfer-progress clean checkstyle:checkstyle

      - name: Upload Checkstyle analysis to Github Actions
        uses: jwgmeligmeyling/checkstyle-github-action@master
        with:
          path: '**/checkstyle-result.xml'