name: Backend Service Continuous Integration - Main

on:
  pull_request:
    branches:
      - main # Run the workflow only on pull requests to the main branch
    paths:
      - 'backend/**' # Workflow triggered on changes to code
      - '.github/workflows/backend_ci.yml'

jobs:
  build:
    uses: ./.github/workflows/backend-ci-build.yml

  test:
    uses: ./.github/workflows/backend-ci-test.yml