name: Continuous Integration - Backend

on:
  pull_request:
    branches:
      - main # Run the workflow only on pull requests to the main branch
    paths:
      - 'backend/**' # Workflow triggered on changes to code
      - '.github/workflows/backend_ci.yml'

jobs:

  build-1:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: .

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'corretto'

      - name: Build with Maven
        run: mvn clean install -q -DskipTests -T 5

  junit-2-1:
    runs-on: ubuntu-latest

    needs: [build-1]

    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'corretto'

      - name: Test Junit with Maven
        run: mvn --no-transfer-progress clean test

      - name: Generate Coverage Report
        run: mvn --no-transfer-progress jacoco:report

      - name: Archive Test Results
        uses: actions/upload-artifact@v4.3.3
        with:
          name: junit-test-results
          path: backend/target/surefire-reports/*.xml

      - name: Archive Coverage Report
        uses: actions/upload-artifact@v4.3.3
        with:
          name: jacoco-coverage-report
          path: backend/target/site/jacoco

      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: backend/target/site/jacoco/jacoco.xml
          fail_ci_if_error: false

  codeql-2-2:
    runs-on: ubuntu-latest

    needs: [build-1]

    defaults:
      run:
        working-directory: .

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: java-kotlin

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'corretto'

      - name: Build with Maven
        run: mvn clean install -q -DskipTests -T 5

      - name: Analyze with CodeQL
        uses: github/codeql-action/analyze@v3

  spotbugs-2-3:
    runs-on: ubuntu-latest

    needs: [ build-1 ]

    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'corretto'

      - name: Build and Run SpotBugs
        run: |
          mvn --no-transfer-progress clean compile spotbugs:spotbugs

      - name: Upload SpotBugs Findings
        uses: jwgmeligmeyling/spotbugs-github-action@master
        with:
          path: backend/target/spotbugsXml.xml


  pmd-2-3:
    runs-on: ubuntu-latest

    needs: [ build-1 ]

    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'corretto'

      - name: Build with Maven
        run: mvn  --no-transfer-progress -B verify pmd:pmd

      - uses: jwgmeligmeyling/pmd-github-action@master
        with:
          path: '**/pmd.xml'